"""rules/horde.nyr (compiled into riftstone.rules.horde) sets exactly the group fields encounter.plan set
by hand before the rule moved into NYR-Lang, for every total, spawn point count and story window."""
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from riftstone import encounter  # noqa: E402
from riftstone.rules import horde  # noqa: E402

STORIES = (None, "", "any", "pre", "post")


def before(total: int, points: int, story) -> tuple[dict, bool]:
    """The hand-written code this rule replaced (encounter.py at 38f45f3), as the oracle."""
    new = {}
    horde_ = total > points
    if horde_:
        new["mSetCountMax"] = total
        new["mRspnCondition.mRspnType"] = 5
        new["mRspnCondition.mRspnDay"] = 0
        new["mRspnCondition.mRspnProb"] = new["mRspnCondition.mRspnProbAdd"] = new["mRspnCondition.mRspnForceRspn"] = 0
    else:
        new["mSetCountMax"] = -1
    if story:
        # The hand-written code wrote "any" 0..0 and "post" 7800..0, reading an end of 0 as "no end".  The game reads
        # the window as it stands (its whole story is 0..27999, its post-Dragon groups 7800..27999), so those groups
        # loaded only at a new game's very start, or never: the oracle keeps its fields and takes the game's windows.
        new["mAppearBgn"], new["mAppearEnd"] = {"any": (0, 27999), "pre": (0, 7799), "post": (7800, 27999)}[story]
    return new, horde_


def after(total: int, points: int, story) -> tuple[dict, bool]:
    """What encounter.plan now does with the rules' result."""
    ruled = horde.evaluate({"total": total, "points": points, "story": encounter.STORY_CODES.get(story, 0)})
    new = {encounter.HORDE_FIELDS[u.name]: int(u.value) for u in ruled.updates}
    return new, any(s.id == horde.CONSTANTS["Horde"] for s in ruled.signals)


class HordeRules(unittest.TestCase):
    def test_every_case_matches_the_code_it_replaced(self):
        totals = list(range(1, 64)) + [99, 100, 101, 500, 9998, 9999]
        cases = 0
        for total in totals:
            for points in range(1, min(total, encounter.MAX_POINTS) + 1):
                for story in STORIES:
                    got, want = after(total, points, story), before(total, points, story)
                    self.assertEqual(got, want, (total, points, story))
                    for v in got[0].values():
                        self.assertIs(type(v), int)
                    cases += 1
        self.assertGreater(cases, 5000)

    def test_the_story_windows_are_the_games_own(self):
        # measured 2026-09-27 over the game's enemy group lists (scenario condition on): 218 groups 0..27999 (the whole
        # story), 184 groups 0..7799 (before the Dragon), 41 groups 7800..27999 (after it), none ending at 0
        windows = {story: (after(1, 1, story)[0]["mAppearBgn"], after(1, 1, story)[0]["mAppearEnd"])
                   for story in ("any", "pre", "post")}
        self.assertEqual(windows, {"any": (0, 27999), "pre": (0, 7799), "post": (7800, 27999)})
        for bgn, end in windows.values():
            self.assertLessEqual(bgn, end)

    def test_constants_the_rest_of_encounter_uses(self):
        self.assertEqual(encounter.HORDE_RESPAWN, 5)
        self.assertEqual(set(encounter.HORDE_FIELDS), set(horde.OUTPUTS))
        self.assertEqual(horde.INPUTS, ("total", "points", "story"))

    def test_the_generated_module_says_where_it_comes_from(self):
        text = Path(horde.__file__).read_text(encoding="utf-8")
        self.assertTrue(text.startswith("# Generated by nyrc"), text[:80])
        self.assertIn("from rules/horde.nyr -- do not edit.", text.splitlines()[0])


if __name__ == "__main__":
    unittest.main()
