"""Game rules written in NYR-Lang (the .nyr sources in rules/ at the repository root).

Every module here except this one is generated by nyrc from those sources, as nyr.json lists them:
never edit one by hand. Change the .nyr source, run ``<path> --build`` in the
repository root and commit both; tools\\test_all.cmd fails while a module is out of date.
Each module needs only the standard library.
"""
