# Generated by nyrc 0.2.0 (NYR-Lang) from rules/beats.nyr -- do not edit.
# source sha256 cd1bd6368178c907e486b7d3791db9adaafd6818b1293d5b0e1abc32c73c5a77
"""Rules compiled from rules/beats.nyr by nyrc 0.2.0.

evaluate(ctx) returns a Result: the spawns, signals and updates of every rule whose condition
holds, in rule order.  ctx maps every name in INPUTS to a number and every name in
EXTERNAL_SETS to a collection of numbers.  Updates name the OUTPUTS they change; the host
applies them (op 'set' replaces the value, 'add' adds to it).
Try it:  python <this file> name=value ...   (an external set: name=1,2,3)
"""
from __future__ import annotations

import json
import math
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Optional

INPUTS: tuple[str, ...] = ('beat', 'depth')
EXTERNAL_SETS: tuple[str, ...] = ()
OUTPUTS: tuple[str, ...] = ('tier_lo', 'tier_hi', 'total', 'points', 'spread', 'room')
CONSTANTS: dict[str, Any] = {
    'Fight': 1,
    'Ambush': 2,
    'Horde': 3,
    'Guardian': 4,
    'Boss': 5,
}
SETS: dict[str, frozenset[float]] = {}


@dataclass(frozen=True)
class EntitySpawn:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Signal:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Update:
    name: str
    op: str
    value: float


@dataclass
class Result:
    spawns: list[EntitySpawn] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    updates: list[Update] = field(default_factory=list)


def _floor(v):
    if v != v or v in (math.inf, -math.inf):
        return v
    r = float(math.floor(v))
    return math.copysign(r, v) if r == 0 else r        # a zero keeps v's sign, as in IEEE


# rule 0 (line 20): [beat == 1]
def rule_0(x: Mapping[str, Any]) -> bool:
    return x['beat'] == 1.0


# rule 1 (line 24): [beat == 2]
def rule_1(x: Mapping[str, Any]) -> bool:
    return x['beat'] == 2.0


# rule 2 (line 28): [beat == 3]
def rule_2(x: Mapping[str, Any]) -> bool:
    return x['beat'] == 3.0


# rule 3 (line 32): [beat == 4]
def rule_3(x: Mapping[str, Any]) -> bool:
    return x['beat'] == 4.0


# rule 4 (line 35): [beat == 5]
def rule_4(x: Mapping[str, Any]) -> bool:
    return x['beat'] == 5.0


def evaluate(ctx: Mapping[str, Any]) -> Result:
    """The spawns, signals and updates of every rule that holds for ctx, in rule order."""
    missing = [name for name in INPUTS + EXTERNAL_SETS if name not in ctx]
    if missing:
        raise KeyError('missing inputs: ' + ', '.join(missing))
    x: dict[str, Any] = {name: float(ctx[name]) for name in INPUTS}
    x.update((name, ctx[name]) for name in EXTERNAL_SETS)
    out = Result()
    if rule_0(x):  # rule 0, line 20
        # tier_lo <- 1
        out.updates.append(Update('tier_lo', 'set', 1.0))
        # tier_hi <- 1 + floor(depth * 1.999)
        out.updates.append(Update('tier_hi', 'set', 1.0 + _floor(x['depth'] * 1.999)))
        # total <- 3 + floor(depth * 3.999)
        out.updates.append(Update('total', 'set', 3.0 + _floor(x['depth'] * 3.999)))
        # points <- 3 + floor(depth * 3.999)
        out.updates.append(Update('points', 'set', 3.0 + _floor(x['depth'] * 3.999)))
        # spread <- 250
        out.updates.append(Update('spread', 'set', 250.0))
        # room <- 180
        out.updates.append(Update('room', 'set', 180.0))
    if rule_1(x):  # rule 1, line 24
        # tier_lo <- 1
        out.updates.append(Update('tier_lo', 'set', 1.0))
        # tier_hi <- 2
        out.updates.append(Update('tier_hi', 'set', 2.0))
        # total <- 4 + floor(depth * 2.999)
        out.updates.append(Update('total', 'set', 4.0 + _floor(x['depth'] * 2.999)))
        # points <- 4 + floor(depth * 2.999)
        out.updates.append(Update('points', 'set', 4.0 + _floor(x['depth'] * 2.999)))
        # spread <- 350
        out.updates.append(Update('spread', 'set', 350.0))
        # room <- 180
        out.updates.append(Update('room', 'set', 180.0))
    if rule_2(x):  # rule 2, line 28
        # tier_lo <- 1
        out.updates.append(Update('tier_lo', 'set', 1.0))
        # tier_hi <- 1
        out.updates.append(Update('tier_hi', 'set', 1.0))
        # total <- 20 + floor(depth * 20)
        out.updates.append(Update('total', 'set', 20.0 + _floor(x['depth'] * 20.0)))
        # points <- 8
        out.updates.append(Update('points', 'set', 8.0))
        # spread <- 300
        out.updates.append(Update('spread', 'set', 300.0))
        # room <- 350
        out.updates.append(Update('room', 'set', 350.0))
    if rule_3(x):  # rule 3, line 32
        # tier_lo <- 3
        out.updates.append(Update('tier_lo', 'set', 3.0))
        # tier_hi <- 3
        out.updates.append(Update('tier_hi', 'set', 3.0))
        # total <- 1
        out.updates.append(Update('total', 'set', 1.0))
        # points <- 1
        out.updates.append(Update('points', 'set', 1.0))
        # spread <- 250
        out.updates.append(Update('spread', 'set', 250.0))
        # room <- 300
        out.updates.append(Update('room', 'set', 300.0))
    if rule_4(x):  # rule 4, line 35
        # tier_lo <- 4
        out.updates.append(Update('tier_lo', 'set', 4.0))
        # tier_hi <- 4
        out.updates.append(Update('tier_hi', 'set', 4.0))
        # total <- 1
        out.updates.append(Update('total', 'set', 1.0))
        # points <- 1
        out.updates.append(Update('points', 'set', 1.0))
        # spread <- 250
        out.updates.append(Update('spread', 'set', 250.0))
        # room <- 400
        out.updates.append(Update('room', 'set', 400.0))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    """Evaluate for name=value arguments and print the result as JSON."""
    ctx: dict[str, Any] = {}
    for arg in sys.argv[1:] if argv is None else argv:
        name, sep, value = arg.partition('=')
        name = unicodedata.normalize('NFKC', name.strip())
        try:
            if not sep:
                raise ValueError
            if name in EXTERNAL_SETS:
                ctx[name] = frozenset(float(v) for v in value.split(',') if v.strip())
            else:
                ctx[name] = float(value)
        except ValueError:
            print(f'expected name=number (or set=1,2,3), not {arg!r}', file=sys.stderr)
            return 2
    try:
        result = evaluate(ctx)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        return 2
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
