# Generated by nyrc 0.2.0 (NYR-Lang) from rules/horde.nyr -- do not edit.
# source sha256 9b2fe3941a2d2b71b5f46c91f34e7614c238ed7cd4e1f99c28ad174390e0b056
"""Rules compiled from rules/horde.nyr by nyrc 0.2.0.

evaluate(ctx) returns a Result: the spawns, signals and updates of every rule whose condition
holds, in rule order.  ctx maps every name in INPUTS to a number and every name in
EXTERNAL_SETS to a collection of numbers.  Updates name the OUTPUTS they change; the host
applies them (op 'set' replaces the value, 'add' adds to it).
Try it:  python <this file> name=value ...   (an external set: name=1,2,3)
"""
from __future__ import annotations

import json
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Optional

INPUTS: tuple[str, ...] = ('total', 'points', 'story')
EXTERNAL_SETS: tuple[str, ...] = ()
OUTPUTS: tuple[str, ...] = ('set_count_max', 'rspn_type', 'rspn_day', 'rspn_prob', 'rspn_prob_add', 'rspn_force_rspn', 'appear_bgn', 'appear_end')
CONSTANTS: dict[str, Any] = {
    'Horde': 1,
    'HordeRespawn': 5,
    'Dragon': 7800,
    'StoryEnd': 27999,
}
SETS: dict[str, frozenset[float]] = {}


@dataclass(frozen=True)
class EntitySpawn:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Signal:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Update:
    name: str
    op: str
    value: float


@dataclass
class Result:
    spawns: list[EntitySpawn] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    updates: list[Update] = field(default_factory=list)


# rule 0 (line 18): [total > points]
def rule_0(x: Mapping[str, Any]) -> bool:
    return x['total'] > x['points']


# rule 1 (line 22): [total <= points]
def rule_1(x: Mapping[str, Any]) -> bool:
    return x['total'] <= x['points']


# rule 2 (line 29): [story == 1]
def rule_2(x: Mapping[str, Any]) -> bool:
    return x['story'] == 1.0


# rule 3 (line 30): [story == 2]
def rule_3(x: Mapping[str, Any]) -> bool:
    return x['story'] == 2.0


# rule 4 (line 31): [story == 3]
def rule_4(x: Mapping[str, Any]) -> bool:
    return x['story'] == 3.0


def evaluate(ctx: Mapping[str, Any]) -> Result:
    """The spawns, signals and updates of every rule that holds for ctx, in rule order."""
    missing = [name for name in INPUTS + EXTERNAL_SETS if name not in ctx]
    if missing:
        raise KeyError('missing inputs: ' + ', '.join(missing))
    x: dict[str, Any] = {name: float(ctx[name]) for name in INPUTS}
    x.update((name, ctx[name]) for name in EXTERNAL_SETS)
    out = Result()
    if rule_0(x):  # rule 0, line 18
        # S(1)
        out.signals.append(Signal(1, 1, {}))
        # set_count_max <- total
        out.updates.append(Update('set_count_max', 'set', x['total']))
        # rspn_type <- 5
        out.updates.append(Update('rspn_type', 'set', 5.0))
        # rspn_day <- 0
        out.updates.append(Update('rspn_day', 'set', 0.0))
        # rspn_prob <- 0
        out.updates.append(Update('rspn_prob', 'set', 0.0))
        # rspn_prob_add <- 0
        out.updates.append(Update('rspn_prob_add', 'set', 0.0))
        # rspn_force_rspn <- 0
        out.updates.append(Update('rspn_force_rspn', 'set', 0.0))
    if rule_1(x):  # rule 1, line 22
        # set_count_max <- -1
        out.updates.append(Update('set_count_max', 'set', -1.0))
    if rule_2(x):  # rule 2, line 29
        # appear_bgn <- 0
        out.updates.append(Update('appear_bgn', 'set', 0.0))
        # appear_end <- 27999
        out.updates.append(Update('appear_end', 'set', 27999.0))
    if rule_3(x):  # rule 3, line 30
        # appear_bgn <- 0
        out.updates.append(Update('appear_bgn', 'set', 0.0))
        # appear_end <- 7799
        out.updates.append(Update('appear_end', 'set', 7799.0))
    if rule_4(x):  # rule 4, line 31
        # appear_bgn <- 7800
        out.updates.append(Update('appear_bgn', 'set', 7800.0))
        # appear_end <- 27999
        out.updates.append(Update('appear_end', 'set', 27999.0))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    """Evaluate for name=value arguments and print the result as JSON."""
    ctx: dict[str, Any] = {}
    for arg in sys.argv[1:] if argv is None else argv:
        name, sep, value = arg.partition('=')
        name = unicodedata.normalize('NFKC', name.strip())
        try:
            if not sep:
                raise ValueError
            if name in EXTERNAL_SETS:
                ctx[name] = frozenset(float(v) for v in value.split(',') if v.strip())
            else:
                ctx[name] = float(value)
        except ValueError:
            print(f'expected name=number (or set=1,2,3), not {arg!r}', file=sys.stderr)
            return 2
    try:
        result = evaluate(ctx)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        return 2
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
