# Generated by nyrc 0.2.0 (NYR-Lang) from rules/multiply.nyr -- do not edit.
# source sha256 88ec63c372459109259e788f4e069ebe7e06663a2e173ed241b94c64160da1e3
"""Rules compiled from rules/multiply.nyr by nyrc 0.2.0.

evaluate(ctx) returns a Result: the spawns, signals and updates of every rule whose condition
holds, in rule order.  ctx maps every name in INPUTS to a number and every name in
EXTERNAL_SETS to a collection of numbers.  Updates name the OUTPUTS they change; the host
applies them (op 'set' replaces the value, 'add' adds to it).
Try it:  python <this file> name=value ...   (an external set: name=1,2,3)
"""
from __future__ import annotations

import json
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Optional

INPUTS: tuple[str, ...] = ('eligible', 'factor', 'free', 'cap')
EXTERNAL_SETS: tuple[str, ...] = ()
OUTPUTS: tuple[str, ...] = ('copies', 'set_count_max')
CONSTANTS: dict[str, Any] = {
    'MaxTotal': 9999,
}
SETS: dict[str, frozenset[float]] = {}


@dataclass(frozen=True)
class EntitySpawn:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Signal:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Update:
    name: str
    op: str
    value: float


@dataclass
class Result:
    spawns: list[EntitySpawn] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    updates: list[Update] = field(default_factory=list)


def _min(*values):
    r = values[0]
    for v in values[1:]:
        r = r if r < v else v
    return r


# rule 0 (line 17): [eligible > 0]
def rule_0(x: Mapping[str, Any]) -> bool:
    return 0.0 < x['eligible']


# rule 1 (line 18): [eligible <= 0]
def rule_1(x: Mapping[str, Any]) -> bool:
    return x['eligible'] <= 0.0


# rule 2 (line 24): [eligible > 0] and [cap >= 0]
def rule_2(x: Mapping[str, Any]) -> bool:
    return (0.0 < x['eligible']) and (0.0 <= x['cap'])


def evaluate(ctx: Mapping[str, Any]) -> Result:
    """The spawns, signals and updates of every rule that holds for ctx, in rule order."""
    missing = [name for name in INPUTS + EXTERNAL_SETS if name not in ctx]
    if missing:
        raise KeyError('missing inputs: ' + ', '.join(missing))
    x: dict[str, Any] = {name: float(ctx[name]) for name in INPUTS}
    x.update((name, ctx[name]) for name in EXTERNAL_SETS)
    out = Result()
    if rule_0(x):  # rule 0, line 17
        # copies <- min(eligible * (factor - 1), free)
        out.updates.append(Update('copies', 'set', _min(x['eligible'] * (x['factor'] - 1.0), x['free'])))
    if rule_1(x):  # rule 1, line 18
        # copies <- 0
        out.updates.append(Update('copies', 'set', 0.0))
    if rule_2(x):  # rule 2, line 24
        # set_count_max <- min(cap * factor, 9999)
        out.updates.append(Update('set_count_max', 'set', _min(x['cap'] * x['factor'], 9999.0)))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    """Evaluate for name=value arguments and print the result as JSON."""
    ctx: dict[str, Any] = {}
    for arg in sys.argv[1:] if argv is None else argv:
        name, sep, value = arg.partition('=')
        name = unicodedata.normalize('NFKC', name.strip())
        try:
            if not sep:
                raise ValueError
            if name in EXTERNAL_SETS:
                ctx[name] = frozenset(float(v) for v in value.split(',') if v.strip())
            else:
                ctx[name] = float(value)
        except ValueError:
            print(f'expected name=number (or set=1,2,3), not {arg!r}', file=sys.stderr)
            return 2
    try:
        result = evaluate(ctx)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        return 2
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
