# Generated by nyrc 0.2.0 (NYR-Lang) from rules/tiers.nyr -- do not edit.
# source sha256 fe3a43a2fe3509a7892e0ee316e67745458bf7d59471becd1e8c5591f10ebffb
"""Rules compiled from rules/tiers.nyr by nyrc 0.2.0.

evaluate(ctx) returns a Result: the spawns, signals and updates of every rule whose condition
holds, in rule order.  ctx maps every name in INPUTS to a number and every name in
EXTERNAL_SETS to a collection of numbers.  Updates name the OUTPUTS they change; the host
applies them (op 'set' replaces the value, 'add' adds to it).
Try it:  python <this file> name=value ...   (an external set: name=1,2,3)
"""
from __future__ import annotations

import json
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Optional

INPUTS: tuple[str, ...] = ('exp', 'boss')
EXTERNAL_SETS: tuple[str, ...] = ()
OUTPUTS: tuple[str, ...] = ('tier', 'critter')
CONSTANTS: dict[str, Any] = {
    'Wolf': 50,
    'Seasoned': 400,
    'Big': 2000,
    'Apex': 10000,
}
SETS: dict[str, frozenset[float]] = {}


@dataclass(frozen=True)
class EntitySpawn:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Signal:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Update:
    name: str
    op: str
    value: float


@dataclass
class Result:
    spawns: list[EntitySpawn] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    updates: list[Update] = field(default_factory=list)


# rule 0 (line 15): [exp < 400]
def rule_0(x: Mapping[str, Any]) -> bool:
    return x['exp'] < 400.0


# rule 1 (line 16): [400 <= exp < 2000]
def rule_1(x: Mapping[str, Any]) -> bool:
    return 400.0 <= x['exp'] < 2000.0


# rule 2 (line 17): [2000 <= exp < 10000]
def rule_2(x: Mapping[str, Any]) -> bool:
    return 2000.0 <= x['exp'] < 10000.0


# rule 3 (line 18): [exp >= 10000]
def rule_3(x: Mapping[str, Any]) -> bool:
    return 10000.0 <= x['exp']


# rule 4 (line 22): [exp == 0] and [boss == 1]
def rule_4(x: Mapping[str, Any]) -> bool:
    return (x['exp'] == 0.0) and (x['boss'] == 1.0)


# rule 5 (line 24): [0 < exp < 50]
def rule_5(x: Mapping[str, Any]) -> bool:
    return 0.0 < x['exp'] < 50.0


# rule 6 (line 25): [exp == 0] or [exp >= 50]
def rule_6(x: Mapping[str, Any]) -> bool:
    return (x['exp'] == 0.0) or (50.0 <= x['exp'])


def evaluate(ctx: Mapping[str, Any]) -> Result:
    """The spawns, signals and updates of every rule that holds for ctx, in rule order."""
    missing = [name for name in INPUTS + EXTERNAL_SETS if name not in ctx]
    if missing:
        raise KeyError('missing inputs: ' + ', '.join(missing))
    x: dict[str, Any] = {name: float(ctx[name]) for name in INPUTS}
    x.update((name, ctx[name]) for name in EXTERNAL_SETS)
    out = Result()
    if rule_0(x):  # rule 0, line 15
        # tier <- 1
        out.updates.append(Update('tier', 'set', 1.0))
    if rule_1(x):  # rule 1, line 16
        # tier <- 2
        out.updates.append(Update('tier', 'set', 2.0))
    if rule_2(x):  # rule 2, line 17
        # tier <- 3
        out.updates.append(Update('tier', 'set', 3.0))
    if rule_3(x):  # rule 3, line 18
        # tier <- 4
        out.updates.append(Update('tier', 'set', 4.0))
    if rule_4(x):  # rule 4, line 22
        # tier <- 4
        out.updates.append(Update('tier', 'set', 4.0))
    if rule_5(x):  # rule 5, line 24
        # critter <- 1
        out.updates.append(Update('critter', 'set', 1.0))
    if rule_6(x):  # rule 6, line 25
        # critter <- 0
        out.updates.append(Update('critter', 'set', 0.0))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    """Evaluate for name=value arguments and print the result as JSON."""
    ctx: dict[str, Any] = {}
    for arg in sys.argv[1:] if argv is None else argv:
        name, sep, value = arg.partition('=')
        name = unicodedata.normalize('NFKC', name.strip())
        try:
            if not sep:
                raise ValueError
            if name in EXTERNAL_SETS:
                ctx[name] = frozenset(float(v) for v in value.split(',') if v.strip())
            else:
                ctx[name] = float(value)
        except ValueError:
            print(f'expected name=number (or set=1,2,3), not {arg!r}', file=sys.stderr)
            return 2
    try:
        result = evaluate(ctx)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        return 2
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
