# Generated by nyrc 0.2.0 (NYR-Lang) from rules/waves.nyr -- do not edit.
# source sha256 2cc34e9052812d64bfe4e66bc96ec1d0687380b40ec1a3c2e58948cd91298b71
"""Rules compiled from rules/waves.nyr by nyrc 0.2.0.

evaluate(ctx) returns a Result: the spawns, signals and updates of every rule whose condition
holds, in rule order.  ctx maps every name in INPUTS to a number and every name in
EXTERNAL_SETS to a collection of numbers.  Updates name the OUTPUTS they change; the host
applies them (op 'set' replaces the value, 'add' adds to it).
Try it:  python <this file> name=value ...   (an external set: name=1,2,3)
"""
from __future__ import annotations

import json
import sys
import unicodedata
from dataclasses import asdict, dataclass, field
from typing import Any, Mapping, Optional

INPUTS: tuple[str, ...] = ('flag', 'keep')
EXTERNAL_SETS: tuple[str, ...] = ()
OUTPUTS: tuple[str, ...] = ('lot_flag', 'flag_no', 'delete_lot_flag', 'set_count_max', 'rspn_type', 'rspn_day', 'rspn_prob', 'rspn_prob_add', 'rspn_force_rspn', 'random_division', 'random_pattern', 'lot_flag2', 'flag_no2')
CONSTANTS: dict[str, Any] = {
    'WaveRespawn': 2,
}
SETS: dict[str, frozenset[float]] = {}


@dataclass(frozen=True)
class EntitySpawn:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Signal:
    id: int
    count: int
    properties: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Update:
    name: str
    op: str
    value: float


@dataclass
class Result:
    spawns: list[EntitySpawn] = field(default_factory=list)
    signals: list[Signal] = field(default_factory=list)
    updates: list[Update] = field(default_factory=list)


# rule 0 (line 18): [flag >= 0]
def rule_0(x: Mapping[str, Any]) -> bool:
    return 0.0 <= x['flag']


# rule 1 (line 23): [keep >= 0]
def rule_1(x: Mapping[str, Any]) -> bool:
    return 0.0 <= x['keep']


# rule 2 (line 24): [keep < 0]
def rule_2(x: Mapping[str, Any]) -> bool:
    return x['keep'] < 0.0


def evaluate(ctx: Mapping[str, Any]) -> Result:
    """The spawns, signals and updates of every rule that holds for ctx, in rule order."""
    missing = [name for name in INPUTS + EXTERNAL_SETS if name not in ctx]
    if missing:
        raise KeyError('missing inputs: ' + ', '.join(missing))
    x: dict[str, Any] = {name: float(ctx[name]) for name in INPUTS}
    x.update((name, ctx[name]) for name in EXTERNAL_SETS)
    out = Result()
    if rule_0(x):  # rule 0, line 18
        # lot_flag <- 1
        out.updates.append(Update('lot_flag', 'set', 1.0))
        # flag_no <- flag
        out.updates.append(Update('flag_no', 'set', x['flag']))
        # delete_lot_flag <- 0
        out.updates.append(Update('delete_lot_flag', 'set', 0.0))
        # set_count_max <- -1
        out.updates.append(Update('set_count_max', 'set', -1.0))
        # rspn_type <- 2
        out.updates.append(Update('rspn_type', 'set', 2.0))
        # rspn_day <- 0
        out.updates.append(Update('rspn_day', 'set', 0.0))
        # rspn_prob <- 0
        out.updates.append(Update('rspn_prob', 'set', 0.0))
        # rspn_prob_add <- 0
        out.updates.append(Update('rspn_prob_add', 'set', 0.0))
        # rspn_force_rspn <- 0
        out.updates.append(Update('rspn_force_rspn', 'set', 0.0))
        # random_division <- 0
        out.updates.append(Update('random_division', 'set', 0.0))
        # random_pattern <- 0
        out.updates.append(Update('random_pattern', 'set', 0.0))
    if rule_1(x):  # rule 1, line 23
        # lot_flag2 <- 1
        out.updates.append(Update('lot_flag2', 'set', 1.0))
        # flag_no2 <- keep
        out.updates.append(Update('flag_no2', 'set', x['keep']))
    if rule_2(x):  # rule 2, line 24
        # lot_flag2 <- 0
        out.updates.append(Update('lot_flag2', 'set', 0.0))
        # flag_no2 <- 0
        out.updates.append(Update('flag_no2', 'set', 0.0))
    return out


def main(argv: Optional[list[str]] = None) -> int:
    """Evaluate for name=value arguments and print the result as JSON."""
    ctx: dict[str, Any] = {}
    for arg in sys.argv[1:] if argv is None else argv:
        name, sep, value = arg.partition('=')
        name = unicodedata.normalize('NFKC', name.strip())
        try:
            if not sep:
                raise ValueError
            if name in EXTERNAL_SETS:
                ctx[name] = frozenset(float(v) for v in value.split(',') if v.strip())
            else:
                ctx[name] = float(value)
        except ValueError:
            print(f'expected name=number (or set=1,2,3), not {arg!r}', file=sys.stderr)
            return 2
    try:
        result = evaluate(ctx)
    except KeyError as e:
        print(e.args[0], file=sys.stderr)
        return 2
    print(json.dumps(asdict(result), indent=2))
    return 0


if __name__ == '__main__':
    sys.exit(main())
