"""Every resource type in the Dragon's Dogma: Dark Arisen PC archives (build 2364871).

Generated by tools/gen_typemap.py from a survey of all 8,536 installed ARC
files.  Each type id is the JAMCRC of the engine class name, which DDDA.exe
carries as a string; the hash is recomputed and checked at import.
"""
from __future__ import annotations

import json
import zlib
from pathlib import Path

# class name, file extension, payload is XFS, vanilla resource count
TYPES_BY_CLASS: tuple[tuple[str, str, bool, int], ...] = (
    ('rAdjustParam', 'ajp', False, 1254),
    ('rAHCamera', 'ahc', True, 3),
    ('rAIEnemyActionParameter', 'eap', False, 245),
    ('rAIFSM', 'fsm', True, 4385),
    ('rAIGoalPlanning', 'gop', True, 2333),
    ('rAIPathConsecutive', 'pcf', False, 1),
    ('rAIPlayerActionParameter', 'aIPlactParam', True, 9),
    ('rAIPresetCharaInfo', 'pci', False, 1),
    ('rAIPresetStudy', 'pcs', False, 1),
    ('rAIPriorityThink', 'prt', True, 162),
    ('rAISensorExt', 'sn2', False, 101),
    ('rAISensorTargetGroup', 'stg', False, 169),
    ('rAIStageActionParameter', 'sap', False, 195),
    ('rAIWayPoint', 'way', False, 309),
    ('rArchive', 'arc', False, 9990),
    ('rAreaHitShape', 'ahs', True, 3),
    ('rArmorModel', 'amr', False, 3),
    ('rArmorModelNpc', 'nmr', False, 2),
    ('rArmorPartsOff', 'aor', False, 1),
    ('rArmorTable', 'atr', False, 2),
    ('rArmorTableNpc', 'ntr', False, 2),
    ('rBlacklist', 'bll', False, 2),
    ('rBodyEdit', 'bed', False, 731),
    ('rBowActParamList', 'bap', True, 3),
    ('rCameraList', 'lcm', False, 195),
    ('rCameraParamList', 'cpl', True, 290),
    ('rCameraQuakeList', 'cql', True, 65),
    ('rChain', 'chn', False, 1),
    ('rChainCol', 'ccl', False, 4),
    ('rCharacterEditPreset', 'gce', True, 1),
    ('rCmcMsgConfig', 'cmc', False, 515),
    ('rCnsIK', 'ik', True, 82),
    ('rCnsShake', 'cnsshake', True, 1),
    ('rCnsTinyChain', 'ctc', False, 25),
    ('rCollision', 'sbc', False, 7362),
    ('rDDFCurve', 'ddfc', True, 26),
    ('rDeformWeightMap', 'dwm', False, 1484),
    ('rEditPatternData', 'epd', True, 1),
    ('rEditPawn', 'edp', False, 731),
    ('rEffect2D', 'e2d', False, 558),
    ('rEffectAnim', 'ean', False, 4059),
    ('rEffectList', 'efl', False, 58307),
    ('rEffectProvider', 'epv', False, 7576),
    ('rEffectStrip', 'efs', False, 322),
    ('rEmShaderParam', 'esp', True, 2),
    ('rEquipLvUp', 'qlv', False, 1),
    ('rFaceEdit', 'fed', False, 731),
    ('rFacePartsEdit', 'fpe', False, 2802),
    ('rFacialAnimation', 'fca', False, 21939),
    ('rFacialPattern', 'fcp', False, 1),
    ('rFullbodyIKHuman', 'fbik_human', True, 1),
    ('rGeometry2', 'geo2', False, 1047),
    ('rGrass2', 'gr2', False, 341),
    ('rGrass2Setting', 'gr2s', False, 949),
    ('rGrassWind', 'grw', False, 872),
    ('rGUI', 'gui', False, 216),
    ('rGUIFont', 'gfd', False, 6),
    ('rGUIIconInfo', 'gii', False, 2),
    ('rGUIMessage', 'gmd', False, 16338),
    ('rHumanEdit', 'hed', False, 729),
    ('rHumanPartsEdit', 'hpe', False, 1749),
    ('rItemCurseCnv', 'cit', False, 1),
    ('rItemLevelParam', 'itemlv', False, 3),
    ('rItemList', 'itl', False, 1),
    ('rItemMix', 'imx', False, 1),
    ('rItemRandParam', 'irp', False, 1),
    ('rItemSetTbl', 'ist', False, 2),
    ('rJointEx', 'jex', False, 150),
    ('rLayout', 'lot', False, 7524),
    ('rLayoutGroupParamList', 'gpl', False, 199),
    ('rLockOnTarget', 'ltg', True, 108),
    ('rMagicActParamList', 'map', False, 77),
    ('rMagicItemActParamList', 'mia', True, 1),
    ('rMapLndMarkPos', 'mlm', True, 3251),
    ('rMaterial', 'mrl', False, 28152),
    ('rModel', 'mod', False, 28094),
    ('rMotionList', 'lmt', False, 4313),
    ('rMsgSerial', 'msl', False, 1220),
    ('rMsgSet', 'mss', False, 1855),
    ('rNavigationMesh', 'nav', False, 53),
    ('rNpcLedgerList', 'nnl', False, 1),
    ('rObjCollision', 'ocl', False, 8629),
    ('rOmList', 'oml', False, 1),
    ('rOutlineParamList', 'olp', True, 1),
    ('rPlAbilityParam', 'ablparam', True, 1),
    ('rPlDefendParam', 'PldefendParam', True, 1),
    ('rPlExp', 'plexp', True, 1),
    ('rPlJobLevel', 'joblvl', True, 9),
    ('rPlJumpParam', 'pjp', True, 1),
    ('rPlLevel', 'lvl', True, 15),
    ('rPlNeckPos', 'PlNeckPos', True, 1),
    ('rPlStamina', 'stm', True, 987),
    ('rPlWeight', 'plw', True, 6),
    ('rPropParam', 'prp', False, 2530),
    ('rQuestCtrlTbl', 'qct', False, 338),
    ('rQuestInfinity', 'qif', False, 1),
    ('rQuestMarker', 'qmk', True, 22),
    ('rQuestReward', 'qr', True, 1),
    ('rQuestSudden', 'qsp', False, 1),
    ('rRagdoll', 'rdd', False, 64),
    ('rRegionStatus', 'rst', False, 110),
    ('rRenderTargetTexture', 'rtex', False, 1699),
    ('rRigidBody', 'rbd', False, 4399),
    ('rRomNoraPawn', 'rnp', True, 33),
    ('rRomPawnInfo', 'rpi', True, 1),
    ('rRomPawnName', 'rpn', True, 1),
    ('rScenario', 'sce', True, 216),
    ('rScheduler', 'sdl', False, 1253),
    ('rShaderPackage', 'spkg', False, 76),
    ('rShlParamList', 'shl', True, 490),
    ('rShopList', 'shp', True, 18),
    ('rSkillList', 'skl', False, 2),
    ('rSky', 'sky', False, 30),
    ('rSoundAttributeSe', 'base', True, 1),
    ('rSoundCurveSet', 'sca', False, 1),
    ('rSoundDirectionalSet', 'sds', False, 1),
    ('rSoundEQ', 'equ', False, 1),
    ('rSoundMotionSe', 'bmse', True, 1251),
    ('rSoundPackage', 'spc', False, 11866),
    ('rSoundPhysicsJoint', 'spj', True, 15),
    ('rSoundPhysicsList', 'spl', False, 1243),
    ('rSoundPhysicsRigidBody', 'spr', True, 1090),
    ('rSoundPhysicsSoftBody', 'sps', True, 2),
    ('rSoundRandom', 'srd', False, 3200),
    ('rSoundRequest', 'srq', False, 9308),
    ('rSoundReverb', 'rev', False, 1),
    ('rSoundReverbTable', 'rvt', True, 35),
    ('rSoundSequenceSe', 'ssq', True, 3062),
    ('rSoundSimpleCurve', 'ssc', True, 260),
    ('rSoundStreamRequest', 'stq', False, 3851),
    ('rSoundSubMixer', 'smx', False, 61),
    ('rSoundSubMixerSet', 'sms', True, 1),
    ('rStagePlaceName', 'spn', False, 23),
    ('rStarCatalog', 'stc', False, 14),
    ('rStartPos', 'stp', True, 126),
    ('rStatusParam', 'statusparam', True, 2),
    ('rSwingModel', 'swm', False, 2754),
    ('rTalkMotion', 'tmd', False, 1),
    ('rTargetMotion', 'tmn', False, 1),
    ('rTexture', 'tex', False, 73706),
    ('rVibration', 'vib', False, 1),
    ('rWeatherEffectParam', 'wep', False, 64),
    ('rWeatherFogParam', 'wfp', False, 55),
    ('rZone', 'zon', False, 1251),
)


def jamcrc(name: str) -> int:
    """MT Framework type id: inverted CRC-32 of the class name, top bit clear."""
    return (~zlib.crc32(name.encode("ascii"))) & 0x7FFFFFFF


BY_ID: dict[int, tuple[str, str, bool]] = {jamcrc(c): (c, e, x) for c, e, x, _ in TYPES_BY_CLASS}
BY_EXT: dict[str, int] = {e.lower(): jamcrc(c) for c, e, _, _ in TYPES_BY_CLASS}

# Dragon's Dogma Online's types (tools/gen_typemap_ddo.py), merged where DDDA has no entry.
# Ids are the same hash in both games, so one table serves both.
_DDO = Path(__file__).with_name("data") / "typemap_ddo.json"
DDO_TYPES: tuple[tuple[str, str, bool, int], ...] = ()
if _DDO.is_file():
    DDO_TYPES = tuple(tuple(r) for r in json.loads(_DDO.read_text(encoding="utf-8"))["types"])
    for _c, _e, _x, _n in DDO_TYPES:
        _i = jamcrc(_c)
        if _i not in BY_ID and _e.lower() not in BY_EXT:
            BY_ID[_i] = (_c, _e, _x)
            BY_EXT[_e.lower()] = _i


def extension(type_id: int) -> str:
    """Extension for a type id; unknown ids become their 8-digit hex so nothing is lost."""
    known = BY_ID.get(type_id)
    return known[1] if known else f"{type_id:08x}"


def type_for_extension(ext: str) -> int | None:
    """Type id for an extension, including the 8-digit hex form of unknown ids."""
    ext = ext.lower().lstrip(".")
    if ext in BY_EXT:
        return BY_EXT[ext]
    if len(ext) == 8 and all(c in "0123456789abcdef" for c in ext):
        return int(ext, 16)
    return None


def class_name(type_id: int) -> str:
    known = BY_ID.get(type_id)
    return known[0] if known else f"<unknown {type_id:08x}>"


def is_xfs(type_id: int) -> bool:
    known = BY_ID.get(type_id)
    return bool(known and known[2])
