"""Regenerate src/riftstone/typemap.py from a corpus survey.

The survey (tools/survey_corpus.py) records every resource type id found in
the installed game's archives, the engine class name whose JAMCRC equals the
id (taken from DDDA.exe's own strings), and the payload magic.  Extensions
follow the community names ARCtool and Albam use; where neither lists a type,
the payload magic or class name supplies one.

usage: python tools/gen_typemap.py SURVEY.json [ALBAM_MTFW_INIT.py]
"""
from __future__ import annotations

import json
import re
import sys
import zlib
from pathlib import Path

# Names the community tools use where Albam's table disagrees or is silent.
OVERRIDES = {
    "rNpcLedgerList": "nnl",       # ARCtool's name; Albam lists "nml"
    "rItemCurseCnv": "cit",
    "rItemRandParam": "irp",
    "rQuestSudden": "qsp",
    "rDDFCurve": "ddfc",
    "rSoundPhysicsJoint": "spj",
}


def jamcrc(name: str) -> int:
    return (~zlib.crc32(name.encode("ascii"))) & 0x7FFFFFFF


def albam_table(path: Path) -> dict[int, str]:
    text = path.read_text(encoding="utf-8")
    block = text.split("FILE_ID_TO_EXTENSION = {", 1)[1].split("}", 1)[0]
    return {int(h, 16): e for h, e in re.findall(r"(0x[0-9A-Fa-f]+):\s*\"([^\"]+)\"", block)}


def magic_ext(magic_hex: str) -> str | None:
    raw = bytes.fromhex(magic_hex)
    text = raw.rstrip(b"\0 ").decode("latin-1").lower()
    return text if 2 <= len(text) <= 4 and text.isalnum() else None


def main() -> int:
    survey = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
    albam = albam_table(Path(sys.argv[2])) if len(sys.argv) > 2 else {}
    rows = []
    for t in survey["types"]:
        tid = int(t["type_id"], 16)
        (cls,) = t["class"]
        assert jamcrc(cls) == tid, cls
        magic = t["magics"][0][0]
        ext = OVERRIDES.get(cls) or albam.get(tid) or magic_ext(magic) or cls[1:].lower()
        xfs = magic == "58465300"
        rows.append((cls, ext, xfs, t["count"]))
    exts = [r[1].lower() for r in rows]
    dupes = {e for e in exts if exts.count(e) > 1}
    if dupes:
        raise SystemExit(f"duplicate extensions: {sorted(dupes)}")
    out = ['"""Every resource type in the Dragon\'s Dogma: Dark Arisen PC archives (build 2364871).',
           "",
           "Generated by tools/gen_typemap.py from a survey of all 8,536 installed ARC",
           "files.  Each type id is the JAMCRC of the engine class name, which DDDA.exe",
           "carries as a string; the hash is recomputed and checked at import.",
           '"""',
           "from __future__ import annotations",
           "",
           "import json",
           "import zlib",
           "from pathlib import Path",
           "",
           "# class name, file extension, payload is XFS, vanilla resource count",
           "TYPES_BY_CLASS: tuple[tuple[str, str, bool, int], ...] = ("]
    for cls, ext, xfs, count in sorted(rows, key=lambda r: r[0].lower()):
        out.append(f"    ({cls!r}, {ext!r}, {xfs!r}, {count}),")
    out += [")",
            "",
            "",
            "def jamcrc(name: str) -> int:",
            '    """MT Framework type id: inverted CRC-32 of the class name, top bit clear."""',
            '    return (~zlib.crc32(name.encode("ascii"))) & 0x7FFFFFFF',
            "",
            "",
            "BY_ID: dict[int, tuple[str, str, bool]] = {jamcrc(c): (c, e, x) for c, e, x, _ in TYPES_BY_CLASS}",
            "BY_EXT: dict[str, int] = {e.lower(): jamcrc(c) for c, e, _, _ in TYPES_BY_CLASS}",
            "",
            "# Dragon's Dogma Online's types (tools/gen_typemap_ddo.py), merged where DDDA has no entry.",
            "# Ids are the same hash in both games, so one table serves both.",
            "_DDO = Path(__file__).with_name(\"data\") / \"typemap_ddo.json\"",
            "DDO_TYPES: tuple[tuple[str, str, bool, int], ...] = ()",
            "if _DDO.is_file():",
            "    DDO_TYPES = tuple(tuple(r) for r in json.loads(_DDO.read_text(encoding=\"utf-8\"))[\"types\"])",
            "    for _c, _e, _x, _n in DDO_TYPES:",
            "        _i = jamcrc(_c)",
            "        if _i not in BY_ID and _e.lower() not in BY_EXT:",
            "            BY_ID[_i] = (_c, _e, _x)",
            "            BY_EXT[_e.lower()] = _i",
            "",
            "",
            "def extension(type_id: int) -> str:",
            '    """Extension for a type id; unknown ids become their 8-digit hex so nothing is lost."""',
            "    known = BY_ID.get(type_id)",
            '    return known[1] if known else f"{type_id:08x}"',
            "",
            "",
            "def type_for_extension(ext: str) -> int | None:",
            '    """Type id for an extension, including the 8-digit hex form of unknown ids."""',
            '    ext = ext.lower().lstrip(".")',
            "    if ext in BY_EXT:",
            "        return BY_EXT[ext]",
            '    if len(ext) == 8 and all(c in "0123456789abcdef" for c in ext):',
            "        return int(ext, 16)",
            "    return None",
            "",
            "",
            "def class_name(type_id: int) -> str:",
            "    known = BY_ID.get(type_id)",
            '    return known[0] if known else f"<unknown {type_id:08x}>"',
            "",
            "",
            "def is_xfs(type_id: int) -> bool:",
            "    known = BY_ID.get(type_id)",
            "    return bool(known and known[2])",
            ""]
    target = Path(__file__).resolve().parents[1] / "src" / "riftstone" / "typemap.py"
    target.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {len(rows)} types to {target}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
