"""Write native/loader/restypes.inc: the loader's table of Dark Arisen's resource types by file extension.

    python tools/gen_loader_types.py            write it
    python tools/gen_loader_types.py --check    exit 1 when the file is not what this writes

The loader's archive guard (native/loader/resources.cpp) turns a loose path the game asks for
(nativePC\\id\\credit_02\\credit2_01_99.gmd) into the name and type its archive files it under; the
type is the JAMCRC of the engine class that owns the extension (src/riftstone/typemap.py, every
type in the 8,536 archives of build 2364871).  Generated: never hand-edit restypes.inc.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from riftstone import typemap  # noqa: E402

TARGET = ROOT / "native" / "loader" / "restypes.inc"


def render() -> str:
    lines = ["// Generated by tools/gen_loader_types.py from src/riftstone/typemap.py: never hand-edit.",
             "// Dark Arisen's resource types: the extension a loose resource's path ends in, and the type id",
             "// its archive files it under (the JAMCRC of the engine class that owns the extension).",
             "// (rArchive's .arc is left out: an archive the game cannot open is not a resource in another.)"]
    for cls, ext, _xfs, _count in sorted(typemap.TYPES_BY_CLASS, key=lambda r: (r[1].lower(), r[0])):
        if ext.lower() == "arc":
            continue
        if not ext.isascii() or not ext.replace("_", "").isalnum():
            raise SystemExit(f"{cls}: extension {ext!r} cannot go into a C string as it is")
        lines.append(f'{{L"{ext}", 0x{typemap.jamcrc(cls):08X}u}},  // {cls}')
    return "\r\n".join(lines) + "\r\n"


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        have = TARGET.read_bytes().decode("utf-8") if TARGET.is_file() else ""
        if have.replace("\r\n", "\n") != text.replace("\r\n", "\n"):
            print(f"{TARGET.relative_to(ROOT)} is out of date: run python tools/gen_loader_types.py")
            return 1
        print(f"{TARGET.relative_to(ROOT)} is current ({text.count('{L')} types)")
        return 0
    TARGET.write_bytes(text.encode("utf-8"))
    print(f"wrote {TARGET.relative_to(ROOT)} ({text.count('{L')} types)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
