"""Regenerate the XFS class tables from the installed game.

src/riftstone/xfsclasses.py   class hashes -> engine class names, resolved against
                              identifier strings in DDDA.exe (hash = JAMCRC(name));
                              a hash matching several strings or none is left out
src/riftstone/data/xfs_schema.json
                              every class's property layout as the vanilla XFS
                              resources declare it (one layout per class is
                              checked; a conflict stops the run)

usage: python tools/gen_xfsclasses.py [--game PATH]
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
import sys
import zlib
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from riftstone import corpus  # noqa: E402
from riftstone.game import find_game  # noqa: E402


def jamcrc(s: bytes) -> int:
    return (~zlib.crc32(s)) & 0x7FFFFFFF


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--game")
    args = ap.parse_args()
    game = find_game(args.game)
    exe = game.exe.read_bytes()
    table: dict[int, set[str]] = defaultdict(set)
    for m in re.finditer(rb"[A-Za-z_][A-Za-z0-9_:<>]{2,120}", exe):
        table[jamcrc(m.group(0))].add(m.group(0).decode("ascii"))
    from riftstone import xfs

    hashes: set[int] = set()
    layouts: dict[int, tuple] = {}
    resources = 0
    for r in corpus.resources(game, corpus.xfs_type_ids()):
        resources += 1
        for c in xfs.parse(r.data).classes:
            hashes.add(c.type_id)
            sig = (c.engine_value, tuple((p.name, p.type, p.attr, p.size) for p in c.props))
            if layouts.setdefault(c.type_id, sig) != sig:
                raise SystemExit(f"class {c.type_id:08x} has two layouts; the schema file cannot hold it")
    names = {h: next(iter(table[h])) for h in hashes if len(table.get(h, ())) == 1}
    schema = {"schema": "riftstone.xfs-schema/1",
              "source": {"exe_sha256": hashlib.sha256(exe).hexdigest(), "distinct_xfs_resources": resources},
              "classes": {}}
    for h in sorted(layouts, key=lambda h: names.get(h, f"0x{h:08x}").lower()):
        engine_value, props = layouts[h]
        schema["classes"][names.get(h, f"0x{h:08x}")] = {
            "engine_value": engine_value,
            "props": [[n, xfs.TYPES[t][0], a, s] for n, t, a, s in props]}
    data_dir = Path(__file__).resolve().parents[1] / "src" / "riftstone" / "data"
    data_dir.mkdir(exist_ok=True)
    (data_dir / "xfs_schema.json").write_text(json.dumps(schema, ensure_ascii=False, separators=(",", ":")),
                                              encoding="utf-8", newline="\n")
    lines = ['"""XFS class hashes seen in vanilla Dragon\'s Dogma: Dark Arisen data, with engine names.',
             "",
             "Generated by tools/gen_xfsclasses.py: every class hash declared by a vanilla XFS",
             "resource, resolved against DDDA.exe identifier strings (hash = JAMCRC(name)).",
             '"""',
             "",
             "NAMES: tuple[str, ...] = ("]
    for h in sorted(names, key=lambda h: names[h].lower()):
        lines.append(f"    {names[h]!r},")
    lines += [")", ""]
    out = Path(__file__).resolve().parents[1] / "src" / "riftstone" / "xfsclasses.py"
    out.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"{len(hashes)} class hashes, {len(names)} named -> {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
